site_name: CP-Tricki
site_url: https://cp-tricki.github.io/
repo_url: https://github.com/cp-tricki/cp-tricki.github.io
theme:
  name: material
  language: en
  custom_dir: docs/overrides
  palette:
    primary: brown
    accent: amber
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
  
plugins:
  - search:
      lang: en
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
      
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js