site_name: CP-Tricki
site_url: https://cp-tricki.github.io/
repo_url: https://github.com/cp-tricki/cp-tricki.github.io
repo_name: cp-tricki/cp-tricki.github.io
edit_uri: edit/main/docs/
theme:
  name: material
  language: en
  custom_dir: docs/overrides
  
  palette: 
  - scheme: default
    primary: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode


  - scheme: slate
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
    
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - content.action.view
  
plugins:
  - search:
      lang: en
  - git-committers:
      repository: cp-tricki/cp-tricki.github.io
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
  - toc-md:
      toc_page_title: Contents
      toc_page_description: Usage mkdocs-toc-md
      header_level: 3
      pickup_description_meta: false
      pickup_description_class: false
      output_path: index.md
      output_log: false
      ignore_page_pattern: index.*.md$
      remove_navigation_page_pattern: index.*.md$
      template_dir_path: custom_template
      integrate_mkdocs_static_i18n: true
      shift_header: after_h1_of_index
      extend_module: true
      output_comment: html


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
      
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/commits.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
